version: 2.1
setup: true # Specifies that we will be using dynamic configuration.
orbs:
  orb-tools: circleci/orb-tools@11.5
  shellcheck: circleci/shellcheck@3.1 # Used to lint shell scripts.

filters: &filters
  tags:
    only: /.*/

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/review:
          filters: *filters
      - shellcheck/check:
          filters: *filters
      # UNCOMMENT THIS SECTION WHEN READY TO PUBLISH. (ALSO UNCOMMENT 'requires: [orb-tools/publish]' BELOW)
      - orb-tools/publish:
          orb-name: svinstech/slack-notifier-orb
          vcs-type: << pipeline.project.type >>
          requires:
            [orb-tools/lint, orb-tools/review, orb-tools/pack, shellcheck/check]
          context: orb-publishing
          filters: *filters
      # Triggers the next workflow in the Orb Development Kit.
      - orb-tools/continue:
          pipeline-number: << pipeline.number >>
          vcs-type: << pipeline.project.type >>
          requires: [orb-tools/publish]
          filters: *filters
