version: 2.1
orbs:
  slack-notifier: svinstech/slack-notifier-orb@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@12.0

filters: &filters
  tags:
    only: /.*/

workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - slack-notifier/send-slack-message: 
          header: TESTING SLACK-NOTIFICATION ORB (public)
          # message: "*Here* _is_ `a` <https://www.giantbomb.com/a/uploads/scale_medium/15/153607/3294276-link.png|link>."
          # message: "Here is a variable: ${WEBHOOK_KELLEN_KINCAID}"
          channelWebhookEnvironmentVariables: WEBHOOK_KELLEN_KINCAID
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb_name: svinstech/slack-notifier-orb
          vcs_type: << pipeline.project.type >>
          pub_type: production
          requires:
            - orb-tools/pack
            - slack-notifier/send-slack-message
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

# VS Code Extension Version: 1.4.0
