version: 2.1
orbs:
  slack-notifier: svinstech/slack-notifier-orb@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@12.0

filters: &filters
  tags:
    only: /.*/

jobs:
  send-message-1:
    docker:
      - image: cypress/browsers:latest
      # - image: cimg/base:current
    steps:
      - slack-notifier/send-slack-message: 
          header: TEST - CONTROL
          message: "test 1"
          channel-webhook-environment-variables: WEBHOOK_KELLEN_KINCAID
  send-message-2:
    docker:
      - image: cimg/base:current
    steps:
      - slack-notifier/send-slack-message: 
          header: "\"TEST\" - \"ESCAPED\" \"DOUBLE-QUOTES\"\""
          message: "\"tes\"t\"\"\" 2\""
          channel-webhook-environment-variables: WEBHOOK_KELLEN_KINCAID
  send-message-3:
    docker:
      - image: cimg/base:current
    steps:
      - slack-notifier/send-slack-message: 
          header: TEST - STRING INTERPOLATION
          message: "These are some variables: ${WEBHOOK_KELLEN_KINCAID} ${WEBHOOK_CHANNEL_SLACK_NOTIFIER_PUBLIC}"
          channel-webhook-environment-variables: WEBHOOK_KELLEN_KINCAID
  send-message-4:
    docker:
      - image: cimg/base:current
    steps:
      - slack-notifier/build-status-notification: 
          header: ""
          additional-text: "Empty string header"
          channel-webhook-environment-variables: WEBHOOK_KELLEN_KINCAID
  send-message-5:
    docker:
      - image: cimg/base:current
    steps:
      - slack-notifier/build-status-notification: 
          header: "Empty string message"
          additional-text: ""
          channel-webhook-environment-variables: WEBHOOK_KELLEN_KINCAID
  # send-message-failure:
  #   docker:
  #     - image: cimg/base:current
  #   steps:
  #     - run:
  #         name: "Fail intentionally"
  #         command: exit 1
  #     - slack-notifier/build-status-notification: 
  #         header: "Intentional failure"
  #         when: "on_fail"
  #         channel-webhook-environment-variables: WEBHOOK_KELLEN_KINCAID
  send-no-message-success:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: "This actually shouldn't result in a message"
          command: exit 0
      - slack-notifier/build-status-notification: 
          header: "Should not be seeing me"
          additional-text: ":x: :x: :x:"
          when: "on_fail"
          channel-webhook-environment-variables: WEBHOOK_KELLEN_KINCAID
  send-message-success:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: "Success message"
          command: exit 0
      - slack-notifier/build-status-notification: 
          header: "Hey this is a success notification!"
          when: "on_success"
          channel-webhook-environment-variables: WEBHOOK_KELLEN_KINCAID
  generate-slack-id-lookup-table:
    docker:
      - image: cimg/node:current
    steps:
      - run:
          name: "Generate Slack ID lookup table"
          command: |
            tsc src/scripts/filter_slack_ids.ts && node src/scripts/filter_slack_ids.js NOTIFIER_BOT_TOKEN
      - run:
          name: "Check length of lookup table"
          command: |
            echo ${#cat slackIdLookupTable.json}

workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - send-message-1:
          filters: *filters
      - send-message-2:
          filters: *filters
      - send-message-3:
          filters: *filters
      - send-message-4:
          filters: *filters
      - send-message-5:
          filters: *filters
      # - send-message-failure:
      #     filters: *filters
      - send-no-message-success:
          filters: *filters
      - send-message-success:
          filters: *filters
      - generate-slack-id-lookup-table:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb_name: svinstech/slack-notifier-orb
          vcs_type: << pipeline.project.type >>
          pub_type: production
          requires:
            - orb-tools/pack
            - send-message-1
            - send-message-2
            - send-message-3
            - send-message-4
            - send-message-5
            # - send-message-failure
            - send-no-message-success
            - send-message-success
            - generate-slack-id-lookup-table
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

# VS Code Extension Version: 1.4.0
