version: 2.1
orbs:
  slack-notifier: svinstech/slack-notifier-orb@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@12.0

filters: &filters
  tags:
    only: /.*/

jobs:
  send-message-1:
    docker:
      - image: 'cypress/browsers:latest'
      # - image: cimg/base:current
    steps:
      - slack-notifier/send-slack-message: 
          header: TEST - CONTROL
          message: "test 1"
          channelWebhookEnvironmentVariables: WEBHOOK_KELLEN_KINCAID
  send-message-2:
    docker:
      - image: 'cypress/browsers:latest'
    steps:
      - slack-notifier/send-slack-message: 
          header: "\"TEST\" - \"ESCAPED\" \"DOUBLE-QUOTES\"\""
          message: "\"tes\"t\"\"\" 2\""
          channelWebhookEnvironmentVariables: WEBHOOK_KELLEN_KINCAID
  send-message-3:
    docker:
      - image: 'cypress/browsers:latest'
    steps:
      - slack-notifier/send-slack-message: 
          header: TEST - STRING INTERPOLATION
          message: "This are some variables: ${WEBHOOK_KELLEN_KINCAID} ${WEBHOOK_CHANNEL_SLACK_NOTIFIER_PUBLIC}"
          channelWebhookEnvironmentVariables: WEBHOOK_KELLEN_KINCAID

workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - send-message-1:
          filters: *filters
      - send-message-2:
          filters: *filters
      - send-message-3:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb_name: svinstech/slack-notifier-orb
          vcs_type: << pipeline.project.type >>
          pub_type: production
          requires:
            - orb-tools/pack
            - send-message-1
            - send-message-2
            - send-message-3
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

# VS Code Extension Version: 1.4.0
